name: Kotlin Test Runner

on:
  push:
    branches:
    - feature/github-actions

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Kotlin compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y kotlin

      - name: Compile Kotlin code
        run: |
          kotlinc src/TestRunner.kt src/Test.kt src/mangers/transaction/TransactionManger.kt src/mangers/report/ReportManger.kt TransactionType src/utils/Validator.kt -include-runtime -d out.jar

      - name: Run Tests
        run: java -jar out.jar
